export enum APPS {
    AVISTAMIENTOS = 3,
    VIGIAS = 2,
    MI_ENTORNO = 5,
    ORDENAMIENTO = 4,
    MOVILIDAD = 1,
    HUELLAS = 6,
    CONTENEDORA = 7,
    INFORMATE = 8,
    ECOCIUDADANOS = 9,
    EMPREDEDORES = 10
}